BUGFIX: PIL no longer works on my Feisty machines: PIL disabled.
Currently, both my Feisty Ubuntu's have stopped working with the GUI of
Scyther. So to be on the safe side, PIL is disabled for now, until I've
resolved the problem.

The error is the following:

---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cas/src/scyther-dev/gui/Gui/Scytherthread.py", line 351, in onViewButton
    w = Attackwindow.AttackWindow(btn.claim)
  File "/home/cas/src/scyther-dev/gui/Gui/Attackwindow.py", line 176, in __init__
    self.CreateInteriorWindowComponents()
  File "/home/cas/src/scyther-dev/gui/Gui/Attackwindow.py", line 209, in CreateInteriorWindowComponents
    dp = AttackDisplay(self, self, attacks[0])
  File "/home/cas/src/scyther-dev/gui/Gui/Attackwindow.py", line 73, in __init__
    self.original = Image.open(filename)
  File "/usr/lib/python2.5/site-packages/PIL/Image.py", line 1912, in open
    return factory(fp, filename)
  File "/usr/lib/python2.5/site-packages/PIL/ImageFile.py", line 82, in __init__
    self._open()
  File "/usr/lib/python2.5/site-packages/PIL/EpsImagePlugin.py", line 277, in _open
    raise IOError, "cannot determine EPS bounding box"
IOError: cannot determine EPS bounding box
---------------------------------------------------------------------------

Great. Bounding boxes in eps again.